### ISSUE TITLE
Error: Unknown node [object Object]

### ISSUE THREAD

**Issue by crazy4groovy** [smooth-code/h2x#4]
Hi, wondering if you know why this is failing?

https://runkit.com/crazy4groovy/h2x

**Comment by neoziro** [comment]
I don't know, I copy pasted it locally and I ran it, no error. You should investigate in the source code to see what is going on.

**Comment by crazy4groovy** [comment]
I confirm this works with my local node too. I'll open a runkit ticket.

**Comment by tolmasky** [comment]
The reason this happens is because `h2x-core`(through `h2x-traverse`) and `h2x-plugin-jsx` both individually list `h2x-types` as dependencies. The reason this is an issue is for the following reason:

1. `h2x-types` defines the symbol NODE_TYPE using `Symbol("NODE_TYPE")` (vs. for example `Symbol.for("h2x-types/NODE_TYPE")`)
2. This means that two h2x-types in a node_module tree can not interact, the library fundamentally relies on package-management deduping to ensure that two separate logical requires resolve to the same identical placement, and thus the same copy of the package.
3. RunKit uses npm2-style non-deduping behavior for resolving packages (this is unfortunately the only way to avoid more serious complications with non-deterministic behavior emergent from deduping algorithms. You can read the issue with nom's deduping here: https://docs.npmjs.com/how-npm-works/npm3-nondet, but yarn's also has issues which if anyone is curious I am happy to share but is beyond the scope of this explanation).
4. Thus on RunKit `h2x-core/node_modules/h2x-traverse/node_modules/h2x-types/symbols` !== `h2x-plugin-jsx/node_modules/h2x-types/symbols`, and as such this if check fails:

```javascript
if (node.constructor[_symbols.NODE_TYPE]) return node.constructor[_symbols.NODE_TYPE];
```

Forcing the code down to the getHTMLNodeType section which eventually results in the error.

This is actually not just a problem that exists in RunKit, but a tricky problem that can turn up in many different scenarios, even if you are using a deduping package manager, as you can still end up with two copies of similar packages in these schemes with the right semver range combinations). The traditional way this problem crops up is with constructors not matching (instanceof failing) due to same issue but with entire classes. There are a number of different ways to deal with this:

1. You can use the `facebook/immutable` strategy and use well-known strings instead of symbols. The theory here is that .nodeType could arguably be a property just like .name and .children, no need to store in a symbol. You can set enumerable to false you can still avoid it coming up in for loops, etc. I don't know much about the library so I can't comment about whether this would violate other goals.
2. Use Symbol.for to ensure even different copies of the library end up with the same symbol. This is similar to the string method, and you would theoretically be relying on the uniqueness of the symbol name vs. true object identity, but again, arguably if someone has a symbol named "h2x-types/NODE_TYPE" they probably mean this, and either way its always accessible through require("h2x-types/symbols") anyways, so its not like you can prevent people placing this symbol in arbitrary objects anyways.
3. Make h2x-types a *peerDependency* instead of a *dependency* to explicitly require all libraries use the same copy, instead of incidentally relying on that through deduping.

I hope this clears up why its not working, and I'm happy to answer any questions or provide any other help in getting this up and running on RunKit!

**Comment by crazy4groovy** [comment]
Thanks for tracking that down @tolmasky! Sounds like good advice. I've rarely used `Symbol` myself, so your first solution seems reasonable to me.

@neoziro ?

**Comment by neoziro** [comment]
@tolmasky thank you for investigated it!

Using plain strings instead of symbols is good for me. Feel free to propose a pull request, else I will do it as soon as I have a moment.
